// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.3
// source: auth-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaintText    string                 `protobuf:"bytes,1,opt,name=plaintText,proto3" json:"plaintText,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Expiry        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Scope         string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *Token) GetPlaintText() string {
	if x != nil {
		return x.PlaintText
	}
	return ""
}

func (x *Token) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Token) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Token) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *Token) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type IsAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAuthRequest) Reset() {
	*x = IsAuthRequest{}
	mi := &file_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAuthRequest) ProtoMessage() {}

func (x *IsAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAuthRequest.ProtoReflect.Descriptor instead.
func (*IsAuthRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *IsAuthRequest) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type IsAuthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAuthReply) Reset() {
	*x = IsAuthReply{}
	mi := &file_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAuthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAuthReply) ProtoMessage() {}

func (x *IsAuthReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAuthReply.ProtoReflect.Descriptor instead.
func (*IsAuthReply) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *IsAuthReply) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *IsAuthReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *SignUpRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type SignUpReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token         *Token                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Err           string                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpReply) Reset() {
	*x = SignUpReply{}
	mi := &file_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpReply) ProtoMessage() {}

func (x *SignUpReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpReply.ProtoReflect.Descriptor instead.
func (*SignUpReply) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{5}
}

func (x *SignUpReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SignUpReply) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *SignUpReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{6}
}

func (x *LoginRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token         *Token                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Err           string                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_auth_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{7}
}

func (x *LoginReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginReply) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *LoginReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_auth_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{8}
}

func (x *LogoutRequest) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type LogoutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_auth_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{9}
}

func (x *LogoutReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type ServiceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatusRequest) Reset() {
	*x = ServiceStatusRequest{}
	mi := &file_auth_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatusRequest) ProtoMessage() {}

func (x *ServiceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatusRequest.ProtoReflect.Descriptor instead.
func (*ServiceStatusRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{10}
}

type ServiceStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatusReply) Reset() {
	*x = ServiceStatusReply{}
	mi := &file_auth_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatusReply) ProtoMessage() {}

func (x *ServiceStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatusReply.ProtoReflect.Descriptor instead.
func (*ServiceStatusReply) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceStatusReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ServiceStatusReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_auth_service_proto protoreflect.FileDescriptor

const file_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x12auth-service.proto\x12\x04auth\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x9d\x01\n" +
	"\x05Token\x12\x1e\n" +
	"\n" +
	"plaintText\x18\x01 \x01(\tR\n" +
	"plaintText\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\x122\n" +
	"\x06expiry\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\"2\n" +
	"\rIsAuthRequest\x12!\n" +
	"\x05token\x18\x01 \x01(\v2\v.auth.TokenR\x05token\"B\n" +
	"\vIsAuthReply\x12!\n" +
	"\x05token\x18\x01 \x01(\v2\v.auth.TokenR\x05token\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\"/\n" +
	"\rSignUpRequest\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".auth.UserR\x04user\"Z\n" +
	"\vSignUpReply\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\x05token\x18\x02 \x01(\v2\v.auth.TokenR\x05token\x12\x10\n" +
	"\x03err\x18\x03 \x01(\tR\x03err\".\n" +
	"\fLoginRequest\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".auth.UserR\x04user\"Y\n" +
	"\n" +
	"LoginReply\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\x05token\x18\x02 \x01(\v2\v.auth.TokenR\x05token\x12\x10\n" +
	"\x03err\x18\x03 \x01(\tR\x03err\"2\n" +
	"\rLogoutRequest\x12!\n" +
	"\x05token\x18\x01 \x01(\v2\v.auth.TokenR\x05token\"\x1f\n" +
	"\vLogoutReply\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\"\x16\n" +
	"\x14ServiceStatusRequest\":\n" +
	"\x12ServiceStatusReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err2\x9c\x02\n" +
	"\x04Auth\x122\n" +
	"\x06IsAuth\x12\x13.auth.IsAuthRequest\x1a\x11.auth.IsAuthReply\"\x00\x122\n" +
	"\x06SignUp\x12\x13.auth.SignUpRequest\x1a\x11.auth.SignUpReply\"\x00\x12/\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x10.auth.LoginReply\"\x00\x122\n" +
	"\x06Logout\x12\x13.auth.LogoutRequest\x1a\x11.auth.LogoutReply\"\x00\x12G\n" +
	"\rServiceStatus\x12\x1a.auth.ServiceStatusRequest\x1a\x18.auth.ServiceStatusReply\"\x00B\aZ\x05./;pbb\x06proto3"

var (
	file_auth_service_proto_rawDescOnce sync.Once
	file_auth_service_proto_rawDescData []byte
)

func file_auth_service_proto_rawDescGZIP() []byte {
	file_auth_service_proto_rawDescOnce.Do(func() {
		file_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_service_proto_rawDesc), len(file_auth_service_proto_rawDesc)))
	})
	return file_auth_service_proto_rawDescData
}

var file_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_auth_service_proto_goTypes = []any{
	(*User)(nil),                  // 0: auth.User
	(*Token)(nil),                 // 1: auth.Token
	(*IsAuthRequest)(nil),         // 2: auth.IsAuthRequest
	(*IsAuthReply)(nil),           // 3: auth.IsAuthReply
	(*SignUpRequest)(nil),         // 4: auth.SignUpRequest
	(*SignUpReply)(nil),           // 5: auth.SignUpReply
	(*LoginRequest)(nil),          // 6: auth.LoginRequest
	(*LoginReply)(nil),            // 7: auth.LoginReply
	(*LogoutRequest)(nil),         // 8: auth.LogoutRequest
	(*LogoutReply)(nil),           // 9: auth.LogoutReply
	(*ServiceStatusRequest)(nil),  // 10: auth.ServiceStatusRequest
	(*ServiceStatusReply)(nil),    // 11: auth.ServiceStatusReply
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_auth_service_proto_depIdxs = []int32{
	12, // 0: auth.Token.expiry:type_name -> google.protobuf.Timestamp
	1,  // 1: auth.IsAuthRequest.token:type_name -> auth.Token
	1,  // 2: auth.IsAuthReply.token:type_name -> auth.Token
	0,  // 3: auth.SignUpRequest.user:type_name -> auth.User
	1,  // 4: auth.SignUpReply.token:type_name -> auth.Token
	0,  // 5: auth.LoginRequest.user:type_name -> auth.User
	1,  // 6: auth.LoginReply.token:type_name -> auth.Token
	1,  // 7: auth.LogoutRequest.token:type_name -> auth.Token
	2,  // 8: auth.Auth.IsAuth:input_type -> auth.IsAuthRequest
	4,  // 9: auth.Auth.SignUp:input_type -> auth.SignUpRequest
	6,  // 10: auth.Auth.Login:input_type -> auth.LoginRequest
	8,  // 11: auth.Auth.Logout:input_type -> auth.LogoutRequest
	10, // 12: auth.Auth.ServiceStatus:input_type -> auth.ServiceStatusRequest
	3,  // 13: auth.Auth.IsAuth:output_type -> auth.IsAuthReply
	5,  // 14: auth.Auth.SignUp:output_type -> auth.SignUpReply
	7,  // 15: auth.Auth.Login:output_type -> auth.LoginReply
	9,  // 16: auth.Auth.Logout:output_type -> auth.LogoutReply
	11, // 17: auth.Auth.ServiceStatus:output_type -> auth.ServiceStatusReply
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_auth_service_proto_init() }
func file_auth_service_proto_init() {
	if File_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_service_proto_rawDesc), len(file_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_service_proto_goTypes,
		DependencyIndexes: file_auth_service_proto_depIdxs,
		MessageInfos:      file_auth_service_proto_msgTypes,
	}.Build()
	File_auth_service_proto = out.File
	file_auth_service_proto_goTypes = nil
	file_auth_service_proto_depIdxs = nil
}
